spring:
  kafka:
    bootstrap-servers: ${KAFKA_INFRA_HOST_IP:localhost}:9092

  main:
    allow-bean-definition-overriding: true
  application:
    name: Stock Application
  datasource:
    url: jdbc:postgresql://${DB_INFRA_HOST_IP:localhost}:5432/supplychain_db
    username: ${POSTGRESQL_USERNAME:orderdemo}
    password: ${POSTGRESQL_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          lob:
            non_contextual_creation: true
        hbm2ddl.auto: update
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

app:
  topic:
    sales-order-consumer: store-sales-topic-north-01
    products: product-master
  auth:
    url: http://${GATEWAY_URL:localhost}:9090/oauth/token
    username: ${AUTH_USERNAME:server-server}
    password: ${AUTH_PASSWORD:server-server}
    grant_type: client_credentials
  order:
    url: http://${GATEWAY_URL:localhost}:9090/v2/orders
  stock:
    url: http://${GATEWAY_URL:localhost}:9090/v2/stock
